# Generated by Django 6.0.6 on 2026-07-07 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, verbose_name='文件名称')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('row_count', models.PositiveIntegerField(verbose_name='数据行数')),
                ('variable_count', models.PositiveIntegerField(verbose_name='变量数量')),
                ('time_range', models.CharField(max_length=255, verbose_name='时间范围')),
                ('sampling_period', models.CharField(max_length=50, verbose_name='采样周期')),
                ('missing_value_ratio', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='缺失值比例')),
                ('outlier_ratio', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='异常值比例')),
                ('file_path', models.CharField(max_length=500, verbose_name='文件路径')),
                ('processing_status', models.CharField(max_length=50, verbose_name='处理状态')),
            ],
            options={
                'verbose_name': '工业时序数据文件',
                'verbose_name_plural': '工业时序数据文件',
                'db_table': 'data_files',
            },
        ),
        migrations.CreateModel(
            name='ScenarioTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario_name', models.CharField(max_length=100, unique=True, verbose_name='场景名称')),
                ('industry_type', models.CharField(max_length=100, verbose_name='行业类型')),
                ('input_variables', models.TextField(verbose_name='输入变量')),
                ('output_variables', models.TextField(verbose_name='输出变量')),
                ('controllable_variables', models.TextField(verbose_name='可控变量')),
                ('disturbance_variables', models.TextField(verbose_name='扰动变量')),
                ('quality_variables', models.TextField(verbose_name='质量变量')),
                ('modeling_objective', models.TextField(verbose_name='建模目标')),
                ('evaluation_metrics', models.TextField(verbose_name='评价指标')),
                ('variable_unit_rules', models.TextField(verbose_name='变量单位规则')),
                ('outlier_rules', models.TextField(verbose_name='异常值规则')),
                ('report_template', models.TextField(verbose_name='报告模板')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '场景模板',
                'verbose_name_plural': '场景模板',
                'db_table': 'scenario_templates',
            },
        ),
        migrations.CreateModel(
            name='CollinearityResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable_a', models.CharField(max_length=160, verbose_name='变量A')),
                ('variable_b', models.CharField(max_length=160, verbose_name='变量B')),
                ('correlation_coefficient', models.DecimalField(decimal_places=4, max_digits=8, verbose_name='相关系数')),
                ('collinearity_level', models.CharField(max_length=50, verbose_name='共线性等级')),
                ('processing_method', models.CharField(max_length=120, verbose_name='处理方式')),
                ('is_retained', models.BooleanField(default=True, verbose_name='是否保留')),
                ('analyzed_at', models.DateTimeField(auto_now_add=True, verbose_name='分析时间')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.datafile', verbose_name='文件ID')),
            ],
            options={
                'verbose_name': '共线性分析结果',
                'verbose_name_plural': '共线性分析结果',
                'db_table': 'collinearity_results',
            },
        ),
        migrations.CreateModel(
            name='CleaningRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('missing_value_method', models.CharField(max_length=120, verbose_name='缺失值处理方式')),
                ('outlier_threshold', models.CharField(max_length=80, verbose_name='异常值阈值')),
                ('resampling_period', models.CharField(max_length=50, verbose_name='重采样周期')),
                ('before_cleaning_count', models.PositiveIntegerField(verbose_name='清洗前数据量')),
                ('after_cleaning_count', models.PositiveIntegerField(verbose_name='清洗后数据量')),
                ('missing_value_ratio', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='缺失值比例')),
                ('outlier_ratio', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='异常值比例')),
                ('cleaning_status', models.CharField(max_length=50, verbose_name='清洗状态')),
                ('cleaned_at', models.DateTimeField(auto_now_add=True, verbose_name='清洗时间')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.datafile', verbose_name='文件ID')),
            ],
            options={
                'verbose_name': '数据清洗记录',
                'verbose_name_plural': '数据清洗记录',
                'db_table': 'cleaning_records',
            },
        ),
        migrations.CreateModel(
            name='AgentReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_agent_output', models.TextField(verbose_name='执行Agent输出')),
                ('review_agent_conclusion', models.TextField(verbose_name='评审Agent结论')),
                ('data_quality_result', models.CharField(max_length=120, verbose_name='数据质量结果')),
                ('dynamic_segment_validity_result', models.CharField(max_length=120, verbose_name='动态段有效性结果')),
                ('lag_compensation_result', models.CharField(max_length=120, verbose_name='时滞补偿结果')),
                ('collinearity_processing_result', models.CharField(max_length=120, verbose_name='共线性处理结果')),
                ('model_fitting_result', models.CharField(max_length=120, verbose_name='模型拟合度结果')),
                ('report_integrity_result', models.CharField(max_length=120, verbose_name='报告完整性结果')),
                ('modification_suggestions', models.TextField(blank=True, verbose_name='修改建议')),
                ('is_passed', models.BooleanField(default=False, verbose_name='是否通过')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True, verbose_name='评审时间')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.datafile', verbose_name='文件ID')),
            ],
            options={
                'verbose_name': 'Agent评审记录',
                'verbose_name_plural': 'Agent评审记录',
                'db_table': 'agent_reviews',
            },
        ),
        migrations.CreateModel(
            name='DynamicSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('dynamic_score', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='动态得分')),
                ('snr_score', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='信噪比得分')),
                ('integrity_score', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='完整性得分')),
                ('abnormal_ratio', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='异常比例')),
                ('overall_score', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='综合评分')),
                ('selected_for_modeling', models.BooleanField(default=False, verbose_name='是否入选建模数据')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.datafile', verbose_name='文件ID')),
            ],
            options={
                'verbose_name': '动态数据段',
                'verbose_name_plural': '动态数据段',
                'db_table': 'dynamic_segments',
            },
        ),
        migrations.CreateModel(
            name='ExportRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_type', models.CharField(max_length=100, verbose_name='导出类型')),
                ('export_file_name', models.CharField(max_length=255, verbose_name='导出文件名')),
                ('export_path', models.CharField(max_length=500, verbose_name='导出路径')),
                ('exported_at', models.DateTimeField(auto_now_add=True, verbose_name='导出时间')),
                ('export_status', models.CharField(max_length=50, verbose_name='导出状态')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.datafile', verbose_name='文件ID')),
            ],
            options={
                'verbose_name': '报告导出记录',
                'verbose_name_plural': '报告导出记录',
                'db_table': 'export_records',
            },
        ),
        migrations.CreateModel(
            name='LagAnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_variable', models.CharField(max_length=160, verbose_name='输入变量')),
                ('output_variable', models.CharField(max_length=160, verbose_name='输出变量')),
                ('optimal_lag', models.CharField(max_length=80, verbose_name='最优时滞')),
                ('correlation_score', models.DecimalField(decimal_places=4, max_digits=8, verbose_name='相关性得分')),
                ('compensation_method', models.CharField(max_length=120, verbose_name='补偿方式')),
                ('analyzed_at', models.DateTimeField(auto_now_add=True, verbose_name='分析时间')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.datafile', verbose_name='文件ID')),
            ],
            options={
                'verbose_name': '时滞分析结果',
                'verbose_name_plural': '时滞分析结果',
                'db_table': 'lag_analysis_results',
            },
        ),
        migrations.CreateModel(
            name='ModelResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(max_length=100, verbose_name='模型类型')),
                ('training_data_source', models.CharField(max_length=120, verbose_name='训练数据来源')),
                ('r2', models.DecimalField(decimal_places=4, max_digits=8, verbose_name='R2')),
                ('rmse', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='RMSE')),
                ('mae', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='MAE')),
                ('fitting_degree', models.DecimalField(decimal_places=4, max_digits=8, verbose_name='拟合度')),
                ('model_parameters', models.TextField(verbose_name='模型参数')),
                ('model_file_path', models.CharField(blank=True, max_length=500, verbose_name='模型文件路径')),
                ('trained_at', models.DateTimeField(auto_now_add=True, verbose_name='训练时间')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.datafile', verbose_name='文件ID')),
            ],
            options={
                'verbose_name': '系统辨识模型结果',
                'verbose_name_plural': '系统辨识模型结果',
                'db_table': 'model_results',
            },
        ),
        migrations.CreateModel(
            name='OptimizationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField(verbose_name='轮次')),
                ('dynamic_segment_threshold', models.DecimalField(decimal_places=4, max_digits=8, verbose_name='动态段阈值')),
                ('outlier_threshold', models.CharField(max_length=80, verbose_name='异常值阈值')),
                ('collinearity_threshold', models.DecimalField(decimal_places=4, max_digits=8, verbose_name='共线性阈值')),
                ('lag_search_range', models.CharField(max_length=80, verbose_name='时滞搜索范围')),
                ('min_segment_length', models.CharField(max_length=80, verbose_name='最小数据段长度')),
                ('model_r2', models.DecimalField(decimal_places=4, max_digits=8, verbose_name='模型R2')),
                ('rmse', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='RMSE')),
                ('overall_score', models.DecimalField(decimal_places=4, max_digits=8, verbose_name='综合得分')),
                ('review_result', models.CharField(max_length=120, verbose_name='评审结果')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.datafile', verbose_name='文件ID')),
            ],
            options={
                'verbose_name': '闭环寻优记录',
                'verbose_name_plural': '闭环寻优记录',
                'db_table': 'optimization_runs',
            },
        ),
        migrations.AddField(
            model_name='datafile',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.scenariotemplate', verbose_name='场景ID'),
        ),
        migrations.CreateModel(
            name='StandardCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_item', models.CharField(max_length=120, verbose_name='检查项')),
                ('check_result', models.CharField(max_length=50, verbose_name='检查结果')),
                ('problem_description', models.TextField(blank=True, verbose_name='问题说明')),
                ('repair_suggestion', models.TextField(blank=True, verbose_name='修复建议')),
                ('checked_at', models.DateTimeField(auto_now_add=True, verbose_name='检查时间')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.datafile', verbose_name='文件ID')),
            ],
            options={
                'verbose_name': '数据标准化检查',
                'verbose_name_plural': '数据标准化检查',
                'db_table': 'standard_checks',
            },
        ),
        migrations.CreateModel(
            name='VariableMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_field_name', models.CharField(max_length=120, verbose_name='原始字段名')),
                ('standard_variable_name', models.CharField(max_length=160, verbose_name='标准变量名')),
                ('variable_role', models.CharField(max_length=50, verbose_name='变量角色')),
                ('variable_unit', models.CharField(max_length=50, verbose_name='变量单位')),
                ('upper_limit', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='上限')),
                ('lower_limit', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='下限')),
                ('is_required', models.BooleanField(default=True, verbose_name='是否必填')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.scenariotemplate', verbose_name='场景ID')),
            ],
            options={
                'verbose_name': '统一变量映射',
                'verbose_name_plural': '统一变量映射',
                'db_table': 'variable_mappings',
            },
        ),
    ]
