# Generated by Django 6.0.6 on 2026-09-14 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_prune_unused_scenarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineRunRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='运行ID')),
                ('status', models.CharField(db_index=True, max_length=24, verbose_name='运行状态')),
                ('current_stage', models.CharField(blank=True, max_length=40, verbose_name='当前阶段')),
                ('scenario_id', models.CharField(blank=True, db_index=True, max_length=80, verbose_name='场景ID')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='源文件名')),
                ('snapshot', models.JSONField(default=dict, verbose_name='运行快照')),
                ('artifact_manifest', models.JSONField(default=dict, verbose_name='产物清单')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'pipeline_run_records',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SkillRunRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_run_id', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Skill运行ID')),
                ('pipeline_run_id', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='流水线运行ID')),
                ('status', models.CharField(db_index=True, default='running', max_length=24, verbose_name='运行状态')),
                ('last_sequence', models.PositiveIntegerField(default=0, verbose_name='最后事件序号')),
                ('event_count', models.PositiveIntegerField(default=0, verbose_name='事件数量')),
                ('payload_bytes', models.PositiveBigIntegerField(default=0, verbose_name='事件载荷字节数')),
                ('result', models.JSONField(blank=True, null=True, verbose_name='运行结果')),
                ('error', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'skill_run_records',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ControlApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_id', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='审批ID')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已批准'), ('rejected', '已拒绝'), ('expired', '已过期')], db_index=True, default='pending', max_length=20, verbose_name='审批状态')),
                ('safety_assessment', models.JSONField(default=dict, verbose_name='安全评估')),
                ('requested_by', models.CharField(blank=True, max_length=150, verbose_name='申请人')),
                ('reviewed_by', models.CharField(blank=True, max_length=150, verbose_name='审批人')),
                ('review_comment', models.TextField(blank=True, verbose_name='审批意见')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('candidate_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.optimizationrun')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_approvals', to='core.optimizationstudy')),
            ],
            options={
                'db_table': 'control_approvals',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='RuntimeJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='任务ID')),
                ('job_type', models.CharField(db_index=True, max_length=40, verbose_name='任务类型')),
                ('status', models.CharField(choices=[('queued', '排队中'), ('running', '运行中'), ('completed', '已完成'), ('failed', '失败'), ('cancelled', '已取消')], db_index=True, default='queued', max_length=20, verbose_name='任务状态')),
                ('payload', models.JSONField(default=dict, verbose_name='任务参数')),
                ('result_ref', models.CharField(blank=True, max_length=160, verbose_name='结果引用')),
                ('error', models.TextField(blank=True, verbose_name='错误信息')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='尝试次数')),
                ('max_attempts', models.PositiveSmallIntegerField(default=3, verbose_name='最大尝试次数')),
                ('locked_by', models.CharField(blank=True, max_length=120, verbose_name='执行节点')),
                ('locked_at', models.DateTimeField(blank=True, null=True, verbose_name='锁定时间')),
                ('available_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='可执行时间')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'runtime_jobs',
                'ordering': ('created_at',),
                'indexes': [models.Index(fields=['status', 'available_at'], name='runtime_job_ready_idx')],
            },
        ),
        migrations.CreateModel(
            name='SkillRunEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(verbose_name='事件序号')),
                ('event_type', models.CharField(max_length=64, verbose_name='事件类型')),
                ('stage', models.CharField(max_length=64, verbose_name='阶段')),
                ('status', models.CharField(max_length=32, verbose_name='状态')),
                ('message', models.TextField(blank=True, verbose_name='消息')),
                ('payload', models.JSONField(default=dict, verbose_name='完整事件')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.skillrunrecord')),
            ],
            options={
                'db_table': 'skill_run_events',
                'ordering': ('sequence',),
                'constraints': [models.UniqueConstraint(fields=('run', 'sequence'), name='unique_skill_run_sequence')],
            },
        ),
    ]
