# Generated by Django 6.0.6 on 2026-09-14 06:22

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_pipelinerunrecord_skillrunrecord_controlapproval_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.CharField(db_index=True, max_length=120, unique=True, verbose_name='文档标识')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('source_type', models.CharField(default='builtin', max_length=40, verbose_name='来源类型')),
                ('source_uri', models.CharField(blank=True, max_length=500, verbose_name='来源地址')),
                ('scene_id', models.CharField(blank=True, db_index=True, max_length=80, verbose_name='场景ID')),
                ('version', models.CharField(default='1.0', max_length=40, verbose_name='版本')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('approved', '已审核'), ('retired', '已停用')], db_index=True, default='draft', max_length=20, verbose_name='审核状态')),
                ('checksum', models.CharField(blank=True, max_length=64, verbose_name='内容校验值')),
                ('approved_by', models.CharField(blank=True, max_length=150, verbose_name='审核人')),
                ('effective_at', models.DateTimeField(blank=True, null=True, verbose_name='生效时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'knowledge_documents',
                'ordering': ('scene_id', 'title'),
            },
        ),
        migrations.CreateModel(
            name='RoutingFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField(verbose_name='用户问题')),
                ('scene_id', models.CharField(blank=True, db_index=True, max_length=80, verbose_name='场景ID')),
                ('retrieval_context', models.JSONField(default=dict, verbose_name='检索上下文')),
                ('predicted_skill_ids', models.JSONField(default=list, verbose_name='预测 Skill')),
                ('corrected_skill_ids', models.JSONField(default=list, verbose_name='纠正 Skill')),
                ('outcome', models.CharField(choices=[('accepted', '命中正确'), ('corrected', '已纠正'), ('rejected', '错误召回')], db_index=True, max_length=20, verbose_name='反馈结果')),
                ('reviewed_by', models.CharField(blank=True, max_length=150, verbose_name='复核人')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='复核时间')),
            ],
            options={
                'db_table': 'routing_feedback',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='KnowledgeEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_id', models.CharField(db_index=True, max_length=160, unique=True, verbose_name='实体标识')),
                ('entity_type', models.CharField(db_index=True, max_length=40, verbose_name='实体类型')),
                ('canonical_name', models.CharField(max_length=255, verbose_name='标准名称')),
                ('scene_id', models.CharField(blank=True, db_index=True, max_length=80, verbose_name='场景ID')),
                ('attributes', models.JSONField(default=dict, verbose_name='属性')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('approved', '已审核'), ('retired', '已停用')], db_index=True, default='draft', max_length=20, verbose_name='审核状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('source_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entities', to='core.knowledgedocument')),
            ],
            options={
                'db_table': 'knowledge_entities',
                'ordering': ('entity_type', 'canonical_name'),
            },
        ),
        migrations.CreateModel(
            name='KnowledgeRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_id', models.CharField(db_index=True, max_length=180, unique=True, verbose_name='关系标识')),
                ('predicate', models.CharField(db_index=True, max_length=80, verbose_name='关系类型')),
                ('object_value', models.CharField(blank=True, max_length=500, verbose_name='关系值')),
                ('confidence', models.DecimalField(decimal_places=3, default=Decimal('1.0'), max_digits=4, verbose_name='置信度')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('approved', '已审核'), ('retired', '已停用')], db_index=True, default='draft', max_length=20, verbose_name='审核状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('object_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relations', to='core.knowledgeentity')),
                ('source_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relations', to='core.knowledgedocument')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relations', to='core.knowledgeentity')),
            ],
            options={
                'db_table': 'knowledge_relations',
            },
        ),
        migrations.CreateModel(
            name='SkillKnowledgeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_id', models.CharField(db_index=True, max_length=180, unique=True, verbose_name='规则标识')),
                ('skill_id', models.CharField(db_index=True, max_length=120, verbose_name='Skill ID')),
                ('scene_id', models.CharField(blank=True, db_index=True, max_length=80, verbose_name='场景ID')),
                ('intent_patterns', models.JSONField(default=list, verbose_name='意图表达')),
                ('positive_terms', models.JSONField(default=list, verbose_name='正向术语')),
                ('negative_terms', models.JSONField(default=list, verbose_name='排除术语')),
                ('requires_artifacts', models.JSONField(default=list, verbose_name='前置产物')),
                ('priority', models.PositiveSmallIntegerField(default=50, verbose_name='优先级')),
                ('confidence', models.DecimalField(decimal_places=3, default=Decimal('0.84'), max_digits=4, verbose_name='基础置信度')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('approved', '已审核'), ('retired', '已停用')], db_index=True, default='draft', max_length=20, verbose_name='审核状态')),
                ('rationale', models.TextField(blank=True, verbose_name='规则依据')),
                ('version', models.CharField(default='1.0', max_length=40, verbose_name='版本')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('source_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skill_rules', to='core.knowledgedocument')),
            ],
            options={
                'db_table': 'skill_knowledge_rules',
                'ordering': ('-priority', 'skill_id'),
            },
        ),
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_id', models.CharField(db_index=True, max_length=160, unique=True, verbose_name='知识片段标识')),
                ('ordinal', models.PositiveIntegerField(default=1, verbose_name='片段序号')),
                ('content', models.TextField(verbose_name='知识内容')),
                ('keywords', models.JSONField(default=list, verbose_name='关键词')),
                ('metadata', models.JSONField(default=dict, verbose_name='元数据')),
                ('embedding_ref', models.CharField(blank=True, max_length=255, verbose_name='向量引用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='core.knowledgedocument')),
            ],
            options={
                'db_table': 'knowledge_chunks',
                'ordering': ('document_id', 'ordinal'),
                'constraints': [models.UniqueConstraint(fields=('document', 'ordinal'), name='unique_knowledge_doc_chunk')],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=255, verbose_name='别名')),
                ('normalized_alias', models.CharField(db_index=True, max_length=255, verbose_name='归一化别名')),
                ('language', models.CharField(default='zh-CN', max_length=20, verbose_name='语言')),
                ('priority', models.PositiveSmallIntegerField(default=50, verbose_name='优先级')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='core.knowledgeentity')),
            ],
            options={
                'db_table': 'knowledge_aliases',
                'ordering': ('-priority', 'alias'),
                'constraints': [models.UniqueConstraint(fields=('entity', 'normalized_alias'), name='unique_entity_alias')],
            },
        ),
    ]
