# Generated by Django 6.0.6 on 2026-09-20 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_runtimejob_mcp_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileAsset',
            fields=[
                ('asset_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('owner_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('project', models.CharField(default='A14', max_length=32)),
                ('display_name', models.CharField(max_length=255)),
                ('storage_ref', models.CharField(max_length=255)),
                ('source_type', models.CharField(default='upload', max_length=32)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('size', models.PositiveBigIntegerField()),
                ('rows', models.PositiveIntegerField(null=True)),
                ('columns', models.PositiveIntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='active', max_length=32)),
                ('related_runs', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
