# Generated by Django 6.0.6 on 2026-09-20 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_file_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runtimejob',
            name='status',
            field=models.CharField(choices=[('queued', '排队中'), ('running', '运行中'), ('completed', '已完成'), ('blocked', '已阻断'), ('failed', '失败'), ('cancelled', '已取消'), ('timed_out', '已超时')], db_index=True, default='queued', max_length=20, verbose_name='任务状态'),
        ),
    ]
