"""
Django settings for heating_furnace_apc project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_local_env(path: Path) -> None:
    """Load a simple development .env without overriding deployment variables."""
    if not path.is_file():
        return
    for raw_line in path.read_text(encoding='utf-8').splitlines():
        line = raw_line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue
        key, value = line.split('=', 1)
        key = key.strip()
        if key and key.replace('_', '').isalnum():
            os.environ.setdefault(key, value.strip().strip('"').strip("'"))


_load_local_env(BASE_DIR / '.env')
PROCESSPILOT_RUNTIME_ROOT = Path(os.getenv('PROCESSPILOT_RUNTIME_ROOT', str(BASE_DIR / 'runtime'))).expanduser().resolve()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# Local development has a non-secret fallback; deployments must inject their own key.
SECRET_KEY = os.getenv('PROCESSPILOT_SECRET_KEY', 'processpilot-local-development-only-change-me')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('PROCESSPILOT_DEBUG', '1').strip().lower() in {'1', 'true', 'yes', 'on'}
AGENT_RUNTIME_MODE = os.getenv('AGENT_RUNTIME_MODE', 'hybrid').strip().lower()
if AGENT_RUNTIME_MODE not in {'legacy', 'hybrid', 'skill_runtime'}:
    AGENT_RUNTIME_MODE = 'hybrid'
PROCESSPILOT_REQUIRE_AUTH = os.getenv('PROCESSPILOT_REQUIRE_AUTH', '0' if DEBUG else '1').strip().lower() in {'1', 'true', 'yes', 'on'}
PROCESSPILOT_MCP_URL = os.getenv('PROCESSPILOT_MCP_URL', '').strip()
PROCESSPILOT_MCP_TIMEOUT_SECONDS = float(os.getenv('PROCESSPILOT_MCP_TIMEOUT_SECONDS', '180'))

ALLOWED_HOSTS = [item.strip() for item in os.getenv(
    'PROCESSPILOT_ALLOWED_HOSTS',
    '127.0.0.1,localhost,testserver,*' if os.getenv('PROCESSPILOT_HOST') == '0.0.0.0' else '127.0.0.1,localhost,testserver',
).split(',') if item.strip()]


# Application definition

INSTALLED_APPS = ([
    'simpleui',
] if os.getenv('PROCESSPILOT_SIMPLEUI', '1' if DEBUG else '0').strip().lower() in {'1', 'true', 'yes', 'on'} else []) + [
    'core',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'core.security.ApiAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'heating_furnace_apc.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'heating_furnace_apc.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

if os.getenv('APC_DB_ENGINE', 'sqlite').lower() == 'mysql':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': os.getenv('APC_DB_NAME', 'apc_agent'),
            'USER': os.getenv('APC_DB_USER', 'root'),
            'PASSWORD': os.getenv('APC_DB_PASSWORD', ''),
            'HOST': os.getenv('APC_DB_HOST', '127.0.0.1'),
            'PORT': os.getenv('APC_DB_PORT', '3306'),
            'OPTIONS': {
                'charset': 'utf8mb4',
                'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            },
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / os.getenv('APC_SQLITE_NAME', 'apc_agent.db'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Production transport and cookie settings. TLS may terminate at a trusted proxy.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = os.getenv('PROCESSPILOT_SECURE_SSL_REDIRECT', '0' if DEBUG else '1').strip().lower() in {'1', 'true', 'yes', 'on'}
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'
# Vite uses a same-origin /api proxy, but browsers preserve the frontend Origin
# header on unsafe requests. Trust loopback Vite origins during local development;
# deployments must provide their explicit origins through the environment.
_local_vite_ports = range(5173, 5181)
_default_csrf_origins = ','.join(
    f'http://{host}:{port}' for host in ('127.0.0.1', 'localhost') for port in _local_vite_ports
) if DEBUG else ''
CSRF_TRUSTED_ORIGINS = [item.strip() for item in os.getenv(
    'PROCESSPILOT_CSRF_TRUSTED_ORIGINS', _default_csrf_origins,
).split(',') if item.strip()]
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = 'same-origin'
SECURE_HSTS_SECONDS = int(os.getenv('PROCESSPILOT_HSTS_SECONDS', '0' if DEBUG else '31536000'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG
SECURE_HSTS_PRELOAD = not DEBUG
DATA_UPLOAD_MAX_MEMORY_SIZE = int(os.getenv('PROCESSPILOT_UPLOAD_MEMORY_BYTES', str(5 * 1024 * 1024)))
FILE_UPLOAD_MAX_MEMORY_SIZE = int(os.getenv('PROCESSPILOT_FILE_UPLOAD_MEMORY_BYTES', str(2_621_440)))
PROCESSPILOT_MAX_CSV_ROWS = int(os.getenv('PROCESSPILOT_MAX_CSV_ROWS', '1000000'))
PROCESSPILOT_MAX_CSV_COLUMNS = int(os.getenv('PROCESSPILOT_MAX_CSV_COLUMNS', '500'))
PROCESSPILOT_INLINE_WORKER = os.getenv('PROCESSPILOT_INLINE_WORKER', '1' if DEBUG else '0').strip().lower() in {'1', 'true', 'yes', 'on'}
PROCESSPILOT_JOB_STALE_SECONDS = int(os.getenv('PROCESSPILOT_JOB_STALE_SECONDS', '900'))
DEEPSEEK_API_KEY = os.getenv('DEEPSEEK_API_KEY', '')
DEEPSEEK_API_BASE_URL = os.getenv('DEEPSEEK_API_BASE_URL', 'https://api.deepseek.com')
DEEPSEEK_MODEL = os.getenv('DEEPSEEK_MODEL', 'deepseek-flash')
PROCESSPILOT_LOCAL_LLM_BASE_URL = os.getenv('PROCESSPILOT_LOCAL_LLM_BASE_URL', 'http://127.0.0.1:11434/v1')
PROCESSPILOT_LOCAL_LLM_MODEL = os.getenv('PROCESSPILOT_LOCAL_LLM_MODEL', 'qwen2.5:7b')
PROCESSPILOT_LOCAL_LLM_API_KEY = os.getenv('PROCESSPILOT_LOCAL_LLM_API_KEY', '')
PROCESSPILOT_LLM_TIMEOUT_SECONDS = int(os.getenv('PROCESSPILOT_LLM_TIMEOUT_SECONDS', '90'))
# Control recommendations are advisory by design. Enabling this flag only allows
# approval records; no equipment protocol adapter is shipped or called.
PROCESSPILOT_CONTROL_APPROVALS = os.getenv('PROCESSPILOT_CONTROL_APPROVALS', '1').strip().lower() in {'1', 'true', 'yes', 'on'}


SIMPLEUI_HOME_INFO = False
SIMPLEUI_HOME_QUICK = False
SIMPLEUI_ANALYSIS = False
SIMPLEUI_CONFIG = {
    'system_keep': False,
    'menu_display': ['APC建模数据优选', '认证和授权'],
    'dynamic': False,
    'menus': [
        {
            'name': 'APC建模数据优选',
            'icon': 'fas fa-industry',
            'models': [
                {
                    'name': '场景模板管理',
                    'icon': 'fas fa-layer-group',
                    'url': '/admin/core/scenariotemplate/',
                },
                {
                    'name': '数据文件管理',
                    'icon': 'fas fa-database',
                    'url': '/admin/core/datafile/',
                },
                {
                    'name': '变量映射管理',
                    'icon': 'fas fa-project-diagram',
                    'url': '/admin/core/variablemapping/',
                },
                {
                    'name': '标准检查记录',
                    'icon': 'fas fa-clipboard-check',
                    'url': '/admin/core/standardcheck/',
                },
                {
                    'name': '数据清洗记录',
                    'icon': 'fas fa-broom',
                    'url': '/admin/core/cleaningrecord/',
                },
                {
                    'name': '动态数据段管理',
                    'icon': 'fas fa-chart-line',
                    'url': '/admin/core/dynamicsegment/',
                },
                {
                    'name': '时滞分析结果',
                    'icon': 'fas fa-clock',
                    'url': '/admin/core/laganalysisresult/',
                },
                {
                    'name': '共线性分析结果',
                    'icon': 'fas fa-link',
                    'url': '/admin/core/collinearityresult/',
                },
                {
                    'name': '系统辨识模型',
                    'icon': 'fas fa-cubes',
                    'url': '/admin/core/modelresult/',
                },
                {
                    'name': '闭环寻优任务',
                    'icon': 'fas fa-project-diagram',
                    'url': '/admin/core/optimizationstudy/',
                },
                {
                    'name': '闭环寻优记录',
                    'icon': 'fas fa-sync-alt',
                    'url': '/admin/core/optimizationrun/',
                },
                {
                    'name': 'Agent评审记录',
                    'icon': 'fas fa-robot',
                    'url': '/admin/core/agentreview/',
                },
                {
                    'name': '报告导出记录',
                    'icon': 'fas fa-file-export',
                    'url': '/admin/core/exportrecord/',
                },
                {
                    'name': '知识文档管理',
                    'icon': 'fas fa-book',
                    'url': '/admin/core/knowledgedocument/',
                },
                {
                    'name': '知识实体管理',
                    'icon': 'fas fa-sitemap',
                    'url': '/admin/core/knowledgeentity/',
                },
                {
                    'name': 'Skill 路由规则',
                    'icon': 'fas fa-route',
                    'url': '/admin/core/skillknowledgerule/',
                },
                {
                    'name': '路由反馈复核',
                    'icon': 'fas fa-comments',
                    'url': '/admin/core/routingfeedback/',
                },
            ],
        },
        {
            'app': 'auth',
            'name': '认证和授权',
            'icon': 'fas fa-user-shield',
            'models': [
                {
                    'name': '用户',
                    'icon': 'fas fa-user',
                    'url': '/admin/auth/user/',
                },
                {
                    'name': '用户组',
                    'icon': 'fas fa-users',
                    'url': '/admin/auth/group/',
                },
            ],
        },
    ],
}
