"""
Django settings for heating_furnace_apc project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# Local development has a non-secret fallback; deployments must inject their own key.
SECRET_KEY = os.getenv('PROCESSPILOT_SECRET_KEY', 'processpilot-local-development-only-change-me')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('PROCESSPILOT_DEBUG', '1').strip().lower() in {'1', 'true', 'yes', 'on'}

ALLOWED_HOSTS = [item.strip() for item in os.getenv(
    'PROCESSPILOT_ALLOWED_HOSTS',
    '127.0.0.1,localhost,testserver,*' if os.getenv('PROCESSPILOT_HOST') == '0.0.0.0' else '127.0.0.1,localhost,testserver',
).split(',') if item.strip()]


# Application definition

INSTALLED_APPS = [
    'simpleui',
    'core',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'heating_furnace_apc.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'heating_furnace_apc.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

if os.getenv('APC_DB_ENGINE', 'sqlite').lower() == 'mysql':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': os.getenv('APC_DB_NAME', 'apc_agent'),
            'USER': os.getenv('APC_DB_USER', 'root'),
            'PASSWORD': os.getenv('APC_DB_PASSWORD', ''),
            'HOST': os.getenv('APC_DB_HOST', '127.0.0.1'),
            'PORT': os.getenv('APC_DB_PORT', '3306'),
            'OPTIONS': {
                'charset': 'utf8mb4',
                'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            },
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / os.getenv('APC_SQLITE_NAME', 'apc_agent.db'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'


SIMPLEUI_HOME_INFO = False
SIMPLEUI_HOME_QUICK = False
SIMPLEUI_ANALYSIS = False
SIMPLEUI_CONFIG = {
    'system_keep': False,
    'menu_display': ['APC建模数据优选', '认证和授权'],
    'dynamic': False,
    'menus': [
        {
            'name': 'APC建模数据优选',
            'icon': 'fas fa-industry',
            'models': [
                {
                    'name': '场景模板管理',
                    'icon': 'fas fa-layer-group',
                    'url': '/admin/core/scenariotemplate/',
                },
                {
                    'name': '数据文件管理',
                    'icon': 'fas fa-database',
                    'url': '/admin/core/datafile/',
                },
                {
                    'name': '变量映射管理',
                    'icon': 'fas fa-project-diagram',
                    'url': '/admin/core/variablemapping/',
                },
                {
                    'name': '标准检查记录',
                    'icon': 'fas fa-clipboard-check',
                    'url': '/admin/core/standardcheck/',
                },
                {
                    'name': '数据清洗记录',
                    'icon': 'fas fa-broom',
                    'url': '/admin/core/cleaningrecord/',
                },
                {
                    'name': '动态数据段管理',
                    'icon': 'fas fa-chart-line',
                    'url': '/admin/core/dynamicsegment/',
                },
                {
                    'name': '时滞分析结果',
                    'icon': 'fas fa-clock',
                    'url': '/admin/core/laganalysisresult/',
                },
                {
                    'name': '共线性分析结果',
                    'icon': 'fas fa-link',
                    'url': '/admin/core/collinearityresult/',
                },
                {
                    'name': '系统辨识模型',
                    'icon': 'fas fa-cubes',
                    'url': '/admin/core/modelresult/',
                },
                {
                    'name': '闭环寻优任务',
                    'icon': 'fas fa-project-diagram',
                    'url': '/admin/core/optimizationstudy/',
                },
                {
                    'name': '闭环寻优记录',
                    'icon': 'fas fa-sync-alt',
                    'url': '/admin/core/optimizationrun/',
                },
                {
                    'name': 'Agent评审记录',
                    'icon': 'fas fa-robot',
                    'url': '/admin/core/agentreview/',
                },
                {
                    'name': '报告导出记录',
                    'icon': 'fas fa-file-export',
                    'url': '/admin/core/exportrecord/',
                },
            ],
        },
        {
            'app': 'auth',
            'name': '认证和授权',
            'icon': 'fas fa-user-shield',
            'models': [
                {
                    'name': '用户',
                    'icon': 'fas fa-user',
                    'url': '/admin/auth/user/',
                },
                {
                    'name': '用户组',
                    'icon': 'fas fa-users',
                    'url': '/admin/auth/group/',
                },
            ],
        },
    ],
}
